# Generated by Django 5.0.4 on 2024-05-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=25)),
                ('level', models.IntegerField()),
                ('skill', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='home/')),
            ],
        ),
    ]
