# Generated by Django 5.0.4 on 2024-05-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('sql', 'SQL'), ('react', 'React'), ('spring', 'Spring')], default='python', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(choices=[('front', 'Front-end'), ('back', 'Back-end'), ('grammar', 'Programming Grammar'), ('database', 'Database')], default='grammar', max_length=10),
        ),
    ]
