# Generated by Django 5.0.4 on 2024-05-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_language_profile_level_profile_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(choices=[('front', 'Front-end'), ('back', 'Back-end'), ('grammar', 'Grammar'), ('database', 'Database')], default='grammar', max_length=10),
        ),
    ]
